// Pre-bundles services/vercelApiHandler.ts into api/index.js, the single serverless function
// Vercel deploys. Vercel compiles api/ files in place rather than bundling them, and with
// package.json "type": "module" Node's ESM resolver rejects the extensionless relative
// specifiers used throughout services/ — so the function has to arrive already bundled.
// npm packages stay external: Vercel's file tracing pulls them into the Lambda, and bundling
// them would break the ones that rely on their own on-disk layout.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const entryPoint = path.join(projectRoot, 'services', 'vercelApiHandler.ts');
const outfile = path.join(projectRoot, 'api', 'index.js');

const result = await build({
  entryPoints: [entryPoint],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  packages: 'external',
  banner: {
    js: '// GENERATED by scripts/buildApiFunction.mjs — do not edit.\n'
      + '// Source: services/vercelApiHandler.ts. Rebuild with `npm run build:api`.',
  },
  metafile: true,
});

const bytes = result.metafile.outputs[path.relative(process.cwd(), outfile).replaceAll('\\', '/')]?.bytes;
console.log(`api/index.js bundled${bytes ? ` (${(bytes / 1024).toFixed(1)} kb)` : ''}`);
